database:
  connectionString: postgresql://postgres:postgres@postgres:5432/engine-wizard
  connectionTimeout: 30000

s3:
  url: http://minio:9000
  username: minio
  password: minio
  bucket: engine-wizard

logging:
  level: INFO
  globalLevel: WARNING

mail:
  # enabled: if false = no emails are sent (mailer will not send it, dry run)
  enabled: true
  # from (name, email): default sender email address and name
  name:
  email:
  # provider: smtp | amazonSes | none
  provider: smtp
  smtp:
    host:
    # port: default (empty) = based on security 25/465/587
    port:
    # security: plain | ssl | starttls | tls
    security: starttls
    username: ''
    password: ''
    # SMTP connection timeout (default: 5 seconds)
    timeout: 5
  amazonSes:
    accessKeyId:
    secretAccessKey:
    region:
  rateLimit:
    # time windows in seconds, 0=disabled rate limit
    window: 300
    # max number of messages within the window
    count: 10
  dkim:
    # DKIM key selector
    selector:
    # DKIM private key file (path)
    privkeyFile:

# AWS Configuration used by server (fallback if not provided for mail)
#aws:
#  awsAccessKeyId:
#  awsSecretAccessKey:
#  awsRegion:

#sentry:
#  enabled:
#  workersDsn:

#general:
#  environment: Test
#  clientUrl: http://localhost:3001
