database:
  connectionString: postgresql://postgres:postgres@postgres:5432/engine-wizard
  stripeSize: 1 # used by SE only
  connectionTimeout: 30000
  maxConnections: 10 # used by SE only
  queueTimeout: 500 # used by DW only

s3:
  url: http://minio:9000
  username: minio
  password: minio
  bucket: engine-wizard

logging:
  level: INFO
  globalLevel: WARNING

mail:
  name:
  email:
  host:
  # port: default (empty) = based on security 25/465/587
  port:
  # security: plain | ssl | starttls
  security: starttls
  authEnabled: False
  username: ''
  password: ''
  # legacy "ssl" flag (if security is missing)
  #  - true = security: ssl
  #  - false = security: plain
  ssl: true
  # legacy (if false, no emails are sent - dry-run)
  enabled: true
  rateLimit:
    # time windows in seconds, 0=disabled rate limit
    window: 300
    # max number of messages within the window
    count: 10
  # SMTP connection timeout (default: 5 seconds)
  timeout: 5

#sentry:
#  enabled:
#  workersDsn:

#general:
#  environment: Test
#  clientUrl: http://localhost:3001
