from __future__ import annotations

import typing

from dsw.templating.pot import extract_catalog, render_pot_file

from .model import TemplateFile


if typing.TYPE_CHECKING:
    from .model import Template


class PotFile(typing.NamedTuple):
    data: bytes
    failed_files: list[str]


class _SourceFile(typing.NamedTuple):
    file_name: str
    content: str


def _template_files(template: Template) -> list[_SourceFile]:
    return [
        _SourceFile(file_name=f.filename.as_posix(), content=f.content.decode('utf-8'))
        for f in template.files.values()
        if f.filename.name.endswith(TemplateFile.TEMPLATE_EXTENSIONS)
    ]


def create_pot_file(template: Template) -> PotFile:
    # The same extraction as the document worker uses, so a POT file created
    # locally matches the one generated by the server.
    result = extract_catalog(
        _template_files(template),
        project=template.coordinates,
        version=template.version or '',
        language=template.language,
    )
    return PotFile(data=render_pot_file(result), failed_files=result.failed_files)
