from __future__ import annotations

import io
import typing

import babel
import jinja2.exceptions
import jinja2.ext
from babel.messages.catalog import Catalog
from babel.messages.extract import DEFAULT_KEYWORDS, extract
from babel.messages.pofile import write_po

from . import consts
from .model import TemplateFile


if typing.TYPE_CHECKING:
    from .model import Template


# Must stay in sync with dsw-document-worker (dsw/document_worker/pot.py), so
# that a POT file created locally matches the one generated by the server.
COMMENT_TAGS = ('TRANSLATORS:',)
EXTRACT_METHOD = typing.cast('typing.Any', jinja2.ext.babel_extract)
NO_WRAP = 0
EXTRACT_OPTIONS = {
    'encoding': consts.DEFAULT_ENCODING,
    'extensions': ','.join(consts.JINJA_EXTENSIONS),
    'silent': 'false',
    'newstyle_gettext': 'true',
    'trimmed': str(consts.JINJA_I18N_TRIMMED).lower(),
}


class PotFile(typing.NamedTuple):
    data: bytes
    failed_files: list[str]


def _template_files(template: Template) -> list[TemplateFile]:
    return sorted(
        (f for f in template.files.values()
         if f.filename.name.endswith(TemplateFile.TEMPLATE_EXTENSIONS)),
        key=lambda f: f.filename.as_posix(),
    )


def _make_catalog(template: Template) -> Catalog:
    locale: babel.Locale | None = None
    try:
        locale = babel.Locale.parse(template.language.replace('-', '_'))
    except (ValueError, babel.UnknownLocaleError):
        locale = None
    return Catalog(
        locale=locale,
        domain=consts.DEFAULT_LOCALE_DOMAIN,
        project=template.coordinates,
        version=template.version,
        charset=consts.DEFAULT_ENCODING,
        fuzzy=False,
    )


def create_pot_file(template: Template) -> PotFile:
    catalog = _make_catalog(template)
    failed_files = []
    for file in _template_files(template):
        filename = file.filename.as_posix()
        try:
            messages = list(extract(
                method=EXTRACT_METHOD,
                fileobj=io.BytesIO(file.content),
                keywords=DEFAULT_KEYWORDS,
                comment_tags=COMMENT_TAGS,
                options=EXTRACT_OPTIONS,
            ))
        except jinja2.exceptions.TemplateSyntaxError:
            failed_files.append(filename)
            continue
        for lineno, message, comments, context in messages:
            catalog.add(message, None, [(filename, lineno)],
                        auto_comments=comments, context=context)
    lines = [f'# Translations template for {template.coordinates}.']
    if failed_files:
        lines.append(f'# Skipped files that could not be parsed: {", ".join(failed_files)}')
    catalog.header_comment = '\n'.join(lines) + '\n'
    buffer = io.BytesIO()
    write_po(buffer, catalog, width=NO_WRAP, omit_header=False, sort_output=True)
    return PotFile(data=buffer.getvalue(), failed_files=failed_files)
