name: Code Style

on:
  push:

jobs:
  # Flake 8 for basic code style checks
  flake8:
    name: Flake 8
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: pip
        cache-dependency-path: |
          **/pyproject.toml
          **/requirements*.txt

    - name: Create build info
      run: |
        bash scripts/build-info.sh

    - name: Install Flake8 (5.0.4)
      run: |
        python -m pip install --upgrade pip
        pip install flake8==5.0.4

    - name: Install dependencies
      run: |
        ROOT=$(pwd)
        for package in $(ls packages); do
          echo "-------------------------------------------------"
          echo "- $package"
          echo "-------------------------------------------------"
          cd "$ROOT/packages/$package"
          pip install -r requirements.txt
          make local-deps
          echo "================================================="
        done

    - name: Install package
      run: |
        for package in $(ls packages); do
          echo "-------------------------------------------------"
          echo "- $package"
          echo "-------------------------------------------------"
          pip install packages/$package
          echo "================================================="
        done

    - name: Lint with flake8
      run: |
        flake8 packages --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 packages --count --max-complexity=12 --max-line-length=130 --statistics

  # Typing checks with MyPy
  typing:
    name: Typing
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: pip
        cache-dependency-path: |
          **/pyproject.toml
          **/requirements*.txt

    - name: Create build info
      run: |
        bash scripts/build-info.sh

    - name: Install MyPy (1.4.1)
      run: |
        python -m pip install --upgrade pip
        pip install mypy==1.4.1

    - name: Install dependencies
      run: |
        ROOT=$(pwd)
        for package in $(ls packages); do
          echo "-------------------------------------------------"
          echo "- $package"
          echo "-------------------------------------------------"
          cd "$ROOT/packages/$package"
          pip install -r requirements.txt
          make local-deps
          echo "================================================="
        done

    - name: Install packages
      run: |
        for package in $(ls packages); do
          echo "-------------------------------------------------"
          echo "- $package"
          echo "-------------------------------------------------"
          pip install packages/$package
          echo "================================================="
        done

    - name: Check typing with MyPy
      run: |
        mypy --install-types --ignore-missing-imports --check-untyped-defs --non-interactive packages/*/dsw
