name: Code Style

on:
  push:

jobs:
  # Flake 8 for basic code style checks
  flake8:
    name: Flake 8
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - dsw-command-queue
          - dsw-config
          - dsw-data-seeder
          - dsw-database
          - dsw-document-worker
          - dsw-mailer
          - dsw-storage
          - dsw-tdk

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: pip
        cache-dependency-path: |
          **/pyproject.toml
          **/requirements*.txt

    - name: Create build info
      run: |
        bash scripts/build-info.sh

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        cd packages/${{ matrix.package }}
        pip install -r requirements.txt
        make local-deps

    - name: Install package
      run: |
        pip install packages/${{ matrix.package }}

    - name: Lint with flake8
      run: |
        flake8 packages/${{ matrix.package }} --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 packages/${{ matrix.package }} --count --max-complexity=10 --max-line-length=130 --statistics

  # Typing checks with MyPy
  typing:
    name: Typing
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - dsw-command-queue
          - dsw-config
          - dsw-data-seeder
          - dsw-database
          - dsw-document-worker
          - dsw-mailer
          - dsw-storage
          - dsw-tdk

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: pip
        cache-dependency-path: |
          **/pyproject.toml
          **/requirements*.txt

    - name: Create build info
      run: |
        bash scripts/build-info.sh

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy
        cd packages/${{ matrix.package }}
        pip install -r requirements.txt
        make local-deps

    - name: Install package
      run: |
        cd packages/${{ matrix.package }}
        pip install .

    - name: Typecheck with mypy
      run: |
        cd packages/${{ matrix.package }}
        mypy --install-types --ignore-missing-imports  --non-interactive dsw
