name: Code Style

on:
  push:

jobs:
  # Consistency of version tagging
  version:
    name: Version consts.py
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v6

    - name: Check dsw-data-seeder
      run: |
        bash scripts/check-version.sh \
          packages/dsw-data-seeder/dsw/data_seeder/consts.py \
          packages/dsw-data-seeder/pyproject.toml

    - name: Check dsw-document-worker
      run: |
        bash scripts/check-version.sh \
          packages/dsw-document-worker/dsw/document_worker/consts.py \
          packages/dsw-document-worker/pyproject.toml

    - name: Check dsw-mailer
      run: |
        bash scripts/check-version.sh \
          packages/dsw-mailer/dsw/mailer/consts.py \
          packages/dsw-mailer/pyproject.toml

    - name: Check dsw-tdk
      run: |
        bash scripts/check-version.sh \
          packages/dsw-tdk/dsw/tdk/consts.py \
          packages/dsw-tdk/pyproject.toml

  # CSpell
  cspell:
    name: CSpell
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v6

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24'

    - name: Install CSpell
      run: |
        npm install -g cspell @cspell/dict-python

    - name: Run CSpell
      run: |
        cspell \
          --no-progress \
          --no-summary \
          --config .cspell/cspell.json \
          packages/**/*.py \
          packages/**/*.md \
          packages/**/*.json \
          packages/**/*.toml \
          packages/**/*.yml \
          packages/**/*.yaml

  # Ruff
  ruff:
    name: Ruff
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v6

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Create build info
      run: |
        bash scripts/build-info.sh

    - name: Install the project
      run: uv sync --locked --all-extras --all-packages --no-install-project --dev

    - name: Run Ruff
      run: |
        uv run ruff check

  # Ty
  ty:
    name: Ty
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v6

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Create build info
      run: |
        bash scripts/build-info.sh

    - name: Install the project
      run: uv sync --locked --all-extras --all-packages --no-install-project --dev

    - name: Run Ruff
      run: |
        uv run ty check
