name: Package Release

on:
  release:
    types: [published]

jobs:
  pypi-release:
    name: "PyPi Release"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - dsw-command-queue
          - dsw-config
          - dsw-database
          - dsw-storage
          - dsw-tdk

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: |
          **/pyproject.toml
          **/requirements*.txt

    - name: Prepare Python env
      run: |
        python -m pip install -U pip setuptools wheel

    - name: Create build info
      run: |
        bash scripts/build-info.sh

    - name: Build package sdist
      run: |
        cd packages/${{ matrix.package }}
        python setup.py sdist

    - name: Build package bdist (wheel)
      run: |
        cd packages/${{ matrix.package }}
        python setup.py bdist_wheel

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: packages/${{ matrix.package }}/dist
        print_hash: true
        verbose: true
        skip_existing: true

    - name: Upload release assets
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: packages/${{ matrix.package }}/dist/*
