name: Release

on:
  release:
    types: [published]

jobs:
  pypi-release:
    name: "Python Package Release"
    runs-on: ubuntu-latest

    permissions:
      contents: write  # upload release assets
      id-token: write  # PyPI Trusted Publishing (OIDC)

    strategy:
      fail-fast: false
      matrix:
        package:
          - dsw-command-queue
          - dsw-config
          - dsw-database
          - dsw-models
          - dsw-storage
          - dsw-tdk

    steps:
    - name: Check out repository
      uses: actions/checkout@v7

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Create build info
      run: |
        bash scripts/build-info.sh

    - name: Build distribution packages
      run: |
        uv build --no-create-gitignore --package ${{ matrix.package }}
        ls -lah dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages_dir: ./dist
        print_hash: true
        verbose: true
        skip_existing: true

    - name: Upload release assets
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload "${{ github.event.release.tag_name }}" ./dist/* --clobber

  mail-translations:
    name: "Mail Template Translations"
    runs-on: ubuntu-latest

    permissions:
      contents: write  # upload release assets

    steps:
    - name: Check out repository
      uses: actions/checkout@v7

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Install dependencies
      run: |
        uv sync --all-packages --group translations

    - name: Generate POT files
      run: |
        cd packages/dsw-mailer
        uv run --no-sync make pot

    - name: Upload release assets
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload "${{ github.event.release.tag_name }}" \
          packages/dsw-mailer/templates/locale/*.pot --clobber
