name: Translations

on:
  push:

jobs:
  mail-templates:
    name: Mail Templates
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v7

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Install dependencies
      run: |
        uv sync --all-packages --group translations

    - name: Generate POT files
      run: |
        cd packages/dsw-mailer
        uv run --no-sync make pot

    - name: Upload POT files
      uses: actions/upload-artifact@v7
      with:
        name: mail-pot-files
        path: |
          packages/dsw-mailer/templates/locale/*.pot
