name: Translations

on:
  push:

jobs:
  mail-templates:
    name: Mail Templates
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
        cache: pip
        cache-dependency-path: |
          **/pyproject.toml
          **/requirements*.txt

    - name: Prepare Python env
      run: |
        python -m pip install -U pip setuptools wheel

    - name: Install Babel (2.17.0)
      run: |
        python -m pip install -U babel==2.17.0

    - name: Install dependencies
      run: |
        cd packages/dsw-mailer
        pip install -r requirements.txt
        make local-deps

    - name: Generate POT files
      run: |
        cd packages/dsw-mailer
        make pot

    - name: Upload POT files
      uses: actions/upload-artifact@v4
      with:
        name: mail-pot-files
        path: |
          packages/dsw-mailer/templates/locale/*.pot
